create database if not exists `plinthos`;

use `plinthos`;

-- Table structure for report_request

drop table if exists `request`;
CREATE TABLE `request` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `USER_ID` varchar(50) character set utf8 default NULL,
  `TEMPLATE_PARAMS` mediumtext character set utf8,
  `STATUS` enum('SUBMITTED','RUNNING','EXPIRED','FAILED','COMPLETED','CANCELED','REJECTED') character set utf8 default NULL,
  `PRIORITY` int(11) default NULL,
  `EXPIRATION` datetime default NULL,
  `SUBMISSION_TIME` datetime default NULL,
  `COMPLETION_TIME` datetime default NULL,
  `USER_EMAIL` varchar(64) character set utf8 default NULL,
  `REQUEST_TYPE` varchar(255) character set utf8 default NULL,
  PRIMARY KEY  (`ID`),
  KEY `USERNAME_INDEX` (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


-- Table structure for system_configuration

drop table if exists `system_configuration`;
CREATE TABLE `system_configuration` (
  `ID` int(11) NOT NULL,
  `NAME` varchar(100) default NULL,
  `VALUE` varchar(32) default NULL,
  `LAST_CHANGED` timestamp NOT NULL default CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
  `CREATION_DATE` timestamp NOT NULL default '0000-00-00 00:00:00',
  PRIMARY KEY  (`ID`),
  KEY `NAME_INDEX` (`NAME`(8))
) ENGINE=InnoDB DEFAULT CHARSET=utf8;



-- Table structure for task_registry

drop table if exists `task_registry`;
CREATE TABLE `task_registry` (
  `task_type` varchar(255) NOT NULL,
  `executor_class` varchar(255) NOT NULL,
  `service_provider` varchar(255) default NULL,
  `etc_supported` tinyint(1) NOT NULL      
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- An entry for the sample PlinthOS Service
INSERT INTO task_registry VALUES ('Basic-Statistics','org.plinthos.sample.statistics.service.BasicStatisticsTask','MG',0);

-- Table data for system_configuration

INSERT INTO SYSTEM_CONFIGURATION VALUES (1,'INITIAL_CONTEXT_FACTORY','org.jnp.interfaces.NamingContextFactory',NOW(),NOW());
INSERT INTO SYSTEM_CONFIGURATION VALUES (2,'PROVIDER_URL','jnp://localhost:1099',NOW(),NOW());
INSERT INTO SYSTEM_CONFIGURATION VALUES (3,'RK4_SCHEME_GRID_POINT','5000',NOW(),NOW());
INSERT INTO SYSTEM_CONFIGURATION VALUES (4,'RK4_SCHEME_INTEGRATION_TIME','300',NOW(),NOW());
INSERT INTO SYSTEM_CONFIGURATION VALUES (5,'RK4_DEFAULT_INITIAL_DOF','6',NOW(),NOW());
INSERT INTO SYSTEM_CONFIGURATION VALUES (6,'DEFAULT_DISTILLER_QUEUE_CAPACITY','64',NOW(),NOW());
INSERT INTO SYSTEM_CONFIGURATION VALUES (7,'DISTILLER_QUEUE_TOLERANCE_INDEX','24',NOW(),NOW());
INSERT INTO SYSTEM_CONFIGURATION VALUES (8,'DISTILLER_QUEUE_TOLERANCE','0.05d',NOW(),NOW());
INSERT INTO SYSTEM_CONFIGURATION VALUES (9,'DISTILLER_QUEUE_WEIGHT_TOLERANCE','0.05d',NOW(),NOW());
INSERT INTO SYSTEM_CONFIGURATION VALUES (10,'DISTILLER_QUEUE_IDEAL_WEIGHTS_TYPE','HARDCODED',NOW(),NOW());
INSERT INTO SYSTEM_CONFIGURATION VALUES (11,'WEIGHT_LIST_START_INDEX','1',NOW(),NOW());
INSERT INTO SYSTEM_CONFIGURATION VALUES (12,'WEIGHT_LIST_VALUES','0.50d:0.25d:0.15d:0.05d:0.03d:0.02d',NOW(),NOW());
INSERT INTO SYSTEM_CONFIGURATION VALUES (13,'WEIGHT_LIST_VALUE_SEPERATOR',':',NOW(),NOW());
INSERT INTO SYSTEM_CONFIGURATION VALUES (14,'ALPHA','25.50',NOW(),NOW());
INSERT INTO SYSTEM_CONFIGURATION VALUES (15,'BETA','35.50',NOW(),NOW());
INSERT INTO SYSTEM_CONFIGURATION VALUES (16,'GAMA','90.47',NOW(),NOW());
INSERT INTO SYSTEM_CONFIGURATION VALUES (17,'FIFO_STACK_SIZE','10000',NOW(),NOW());
INSERT INTO SYSTEM_CONFIGURATION VALUES (18,'EXPIRE_TIME_FACTOR','1',NOW(),NOW());
INSERT INTO SYSTEM_CONFIGURATION VALUES (19,'TEMP_DIR_NAME','C:/temp',NOW(),NOW());
INSERT INTO SYSTEM_CONFIGURATION VALUES (20,'MAX_REQUEST_POOL_SIZE','2',NOW(),NOW());
INSERT INTO SYSTEM_CONFIGURATION VALUES (21,'SUPPORT_EMAIL','babis.marmanis@gmail.com',NOW(),NOW());
INSERT INTO SYSTEM_CONFIGURATION VALUES (22,'SERVICES_LIBRARY','plinthos-lib',NOW(),NOW());
